compatible-style 번역
ant-design-korea/ant-design pull request #13
Opened 2024-09-26 12:23 UTC by codingjamee

---
about: .en-US.md, .zh-CN.md 삭제 .md파일 생성
labels: 번역
assignees: 'codingjamee' (허제인)

---

## 요약 설명

### compatible-style 
- Ant Design의 CSS 호환성
- 주요 호환성 이슈와 해결 방법
    - :where 셀렉터 특이성과 브라우저 호환성
    - CSS 논리적 속성 및 브라우저 호환성 설정방법
    - `@layer`를 사용한 우선순위 다운그레이드
- Rem 으로의 변환
- Shadow DOM사용방법
- 써드파티 라이브러리와 호환성 
    - `@layer`설정으로 인한 우선순위 조정
- SSR에서의 사용방법
---

## 고민했던 부분 

모든 영어단어를 일일이 모두 번역하려고 하기 보단  
실제 통용되고 있는 표현이나 용어들은 번역하지 않고 발음되는 한국말로 그대로 옮기기만 했습니다.  
오버라이드 등 덮어씌우다는 의미보다는 오버라이드를 그대로 한국어로 옮기는 것이  
의미가 통할 것이라고 생각했습니다.

2024-09-28 07:08 UTC, owjs3901 requested changes
파일명 변경이 필요합니다

2024-10-07 02:11 UTC, owjs3901 commented on docs/react/compatible-style.en-US.md
> +Ant Design은 [최신 2개 버전의 브라우저](https://browsersl.ist/#q=defaults)를 지원합니다. 만약 레거시 브라우저와의 호환성이 필요한 경우, 실제 필요사항에 따라 다운그레이드를 진행하세요:
`현대 브라우저의 2개의 최신 버전` 등.. 여러 번역이 고민되네요
적절한 번역이 없을까요?
최신 버전은 익숙한데 최신 2개의 버전은 익숙하지 않아서 여러가지로 저도 고민 중인 포인트입니다
다른 분들의 의견 혹은 더 좋은 대안을 함께 고민해봤음 좋겠습니다~

2024-10-07 02:11 UTC, owjs3901 commented on docs/react/compatible-style.en-US.md
> +| [:where 셀렉터](https://developer.mozilla.org/en-US/docs/Web/CSS/:where) | `>=5.0.0` | [caniuse](https://caniuse.com/?search=%3Awhere) | Chrome 88 | `<StyleProvider hashPriority="high">` |
이게 한국 문서가 없는 것은 충격이긴 하네요, 그것과 무관하게 공식 번역인 선택자를 사용하면 어떨까요?

2024-10-07 02:11 UTC, owjs3901 commented on docs/react/compatible-style.en-US.md
> +Ant Design의 CSS-in-JS기능은 기본적으로 특이성을 낮추기 위해 ":where" 셀렉터를 사용합니다. 이것은 사용자가 업그레이드 시 커스텀 스타일을 조정하는 비용을 줄여줍니다. 그러나, ":where" 구문의 호환성은 구 버전의 브라우저에서 좋지 않습니다. ([compatibility](https://developer.mozilla.org/e
특이성 보다는 우선순위가 더 적절하게 읽힐 것 같은데... 사실 특이성 자체도 틀린건 아니긴 합니다, 디테일 하게 조건을 추가하면 우선 순위가 올라가는 것이 CSS라서요, 다른 분들 의견이 궁금합니다

2024-10-07 02:11 UTC, owjs3901 commented on docs/react/compatible-style.en-US.md
> +Ant Design의 CSS-in-JS기능은 기본적으로 특이성을 낮추기 위해 ":where" 셀렉터를 사용합니다. 이것은 사용자가 업그레이드 시 커스텀 스타일을 조정하는 비용을 줄여줍니다. 그러나, ":where" 구문의 호환성은 구 버전의 브라우저에서 좋지 않습니다. ([compatibility](https://developer.mozilla.org/e
`구버전` vs `구 버전` 선택이 필요합니다

2024-10-08 13:32 UTC, lolWK commented on docs/react/compatible-style.en-US.md
> +Ant Design은 [최신 2개 버전의 브라우저](https://browsersl.ist/#q=defaults)를 지원합니다. 만약 레거시 브라우저와의 호환성이 필요한 경우, 실제 필요사항에 따라 다운그레이드를 진행하세요:
[의견] `Ant Design 5.x는 최근 2개 버전의 최신 브라우저를 지원합니다.`

2024-10-08 13:39 UTC, lolWK commented on docs/react/compatible-style.en-US.md
> +Ant Design의 CSS-in-JS기능은 기본적으로 특이성을 낮추기 위해 ":where" 셀렉터를 사용합니다. 이것은 사용자가 업그레이드 시 커스텀 스타일을 조정하는 비용을 줄여줍니다. 그러나, ":where" 구문의 호환성은 구 버전의 브라우저에서 좋지 않습니다. ([compatibility](https://developer.mozilla.org/e
[의견] 저도 우선순위 좋은 것 같습니다~

2024-10-11 00:04 UTC, grapefruit13 reviewed
👍🏻

2024-10-15 14:17 UTC, codingjamee commented on docs/react/compatible-style.en-US.md
> +Ant Design은 [최신 2개 버전의 브라우저](https://browsersl.ist/#q=defaults)를 지원합니다. 만약 레거시 브라우저와의 호환성이 필요한 경우, 실제 필요사항에 따라 다운그레이드를 진행하세요:
최근 2개 버전도 좋은것 같아요 최근 2개 버전의 브라우저를 지원합니다가 조금 더 매끄러울 것같기도 합니다.

2024-10-15 14:20 UTC, codingjamee commented on docs/react/compatible-style.en-US.md
> +Ant Design의 CSS-in-JS기능은 기본적으로 특이성을 낮추기 위해 ":where" 셀렉터를 사용합니다. 이것은 사용자가 업그레이드 시 커스텀 스타일을 조정하는 비용을 줄여줍니다. 그러나, ":where" 구문의 호환성은 구 버전의 브라우저에서 좋지 않습니다. ([compatibility](https://developer.mozilla.org/e
명시도 좋은것 같아요 MDN한글 문서 번역을 참조해서 명시도로 번역해놓겠습니다~

2024-10-18 10:28 UTC, owjs3901 requested changes

2024-10-18 10:28 UTC, owjs3901 commented on docs/react/server-side-rendering.md
> +## 필요에 따른 추출
적절하고 좋네요 수요에 따른 추출보다 훨 좋아 보여요

2024-10-18 10:28 UTC, owjs3901 commented on docs/react/server-side-rendering.md
> +데모는 여기서 볼 수 있습니다:[필요에 따른 css파일 익스포트하기 데모](https://github.com/ant-design/ant-design-examples/tree/main/examples/with-nextjs-generate-css-on-demand)
`익스포트하기`를 `내보내기`로 바꾸는 것은 어떨까요?

2024-10-18 10:28 UTC, owjs3901 commented on docs/react/server-side-rendering.md
> +위의 `_document.tsx`의 도구를 사용하여 필요에 따른 export를 하세요
export 단어에 대한 통일이 필요할 것 같습니다

2024-10-25 07:40 UTC, merged