[ETC] 연관되어있는 다국어를 한국어로 수정
ant-design-korea/ant-design pull request #25
Opened 2024-10-06 18:17 UTC by Banal972

#### Todo

- [x] 404페이지를 하나의 언어로만 나오게 수정하였습니다.

<hr/>

- [x] 모든 locals에 ko 객체를 추가하였습니다.
  - 번역시에 cn, en을 삭제해도 무관합니다.

```ts
const locales = {
  cn: {
    assetsTitle: '组件丰富，选用自如',
    assetsDesc: '大量实用组件满足你的需求，灵活定制与拓展',
    designTitle: '设计语言与研发框架',
    designDesc: '配套生态，让你快速搭建网站应用',
  },
  en: {
    assetsTitle: 'Rich components',
    assetsDesc: 'Practical components to meet your needs, flexible customization and expansion',
    designTitle: 'Design and framework',
    designDesc: 'Supporting ecology, allowing you to quickly build website applications',
  },
  ko: {
    assetsTitle: 'Rich components',
    assetsDesc: 'Practical components to meet your needs, flexible customization and expansion',
    designTitle: 'Design and framework',
    designDesc: 'Supporting ecology, allowing you to quickly build website applications',
  },
};
```

<hr/>

- [x] design token, header 등 여러가지 연관되어있는 모든 기준을 ko로 수정하였습니다.

- [x] token의 번역되는 부분은 `@desc` 기준으로 작성되게 수정하였습니다.

```js
  trackPadding: number;
  /**
   * @desc 여기에 번역하면 됩니다.
   * @descEN 이것은 삭제해도 무관합니다.
   */
  handleBg: string;
```

Gobal Token 부분의 `@name` 같은경우 `@nameKR`을 추가해서 번역하면 됩니다.
```js
  /**
   * @nameKR 이 부분을 추가해서 번역합니다.
   * @nameZH 삭제해도 무관합니다.
   * @nameEN 삭제해도 무관합니다.
   * @desc 이곳에 번역해서 작성합니다.
   * @descEN 삭제해도 무관합니다.
   */
  colorPrimary: string;
```

<hr/>

![image](https://github.com/user-attachments/assets/0e686df8-413d-4b83-9d72-d0cd68af148c)
언어 변경을 못하게하고 한국어만 볼 수 있게 수정헀습니다.

<hr/>

Component/demo/...md 같은경우
\#\# ko-KR만 들어가게 수정하였습니다.
```md
## zh-CN - 삭제하시면 됩니다.

可以在右上角自定义操作项。

## en-US - 삭제하시면 됩니다.

Custom action. 

## ko-KR - 추가후 작성합니다.

커스텀 액션
```

<hr/>

#### Summary

index.md를 기준으로 잡고 만들게 설정해도 index.ko-KR.md이 있으면 둘다 생성되는 것을 발견했습니다.
[https://d.umijs.org/config#locales](https://d.umijs.org/config#locales) 해당 부분을 보면

기준값을 ko-KR로 잡으면 index.md 와 index.ko-KR.md가 같은 기능을 하게 되면서

index.md, index.ko-KR.md 가 둘다 적용이 되기 때문에 둘다 생깁니다.

그래서 일단 component의 index.md만 남기고 index.ko-KR.md은 모두 삭제를 했습니다.

2024-10-07 01:04 UTC, owjs3901 requested changes

2024-10-07 01:04 UTC, owjs3901 commented on .dumi/hooks/useLocation.ts
> +  return path.replace('', '').replace(/\/$/, '');
`replace('', '')` 는 불필요 합니다

2024-10-07 01:04 UTC, owjs3901 commented on .dumi/hooks/useLocation.ts
>    const [, localeType] = useLocale();
조금 더 딥하게 생각해봅시다 useLocale 은 반드시 ko 를 반환하지 않을까요?

2024-10-07 01:04 UTC, owjs3901 commented on .dumi/pages/404/index.tsx
> +      subTitle="Sorry, the page you visited does not exist."
이후 이런 부분들도 추가적인 번역이 필요합니다.

2024-10-07 01:04 UTC, owjs3901 commented on .dumi/pages/theme-editor/index.tsx
> +          locale={lang === 'ko' ? zhCN : enUS}
lang 은 ko가 아닐 확률이 없어야 합니다

2024-10-07 01:04 UTC, owjs3901 commented on .dumi/theme/builtins/ComponentMeta/index.tsx
> +  const isZhCN = lang === 'ko';
lang 은 ko가 아닐 확률이 없어야 합니다

2024-10-07 01:04 UTC, owjs3901 commented on .dumi/theme/builtins/ComponentTokenTable/index.tsx
> +        desc: lang === 'ko' ? meta.desc : meta.descEn,
lang 은 ko가 아닐 확률이 없어야 합니다

2024-10-07 01:04 UTC, owjs3901 commented on .dumi/theme/builtins/LocaleLink/index.tsx
> +      if (localeType === 'ko' && !path.endsWith('-ko')) {
lang 은 ko가 아닐 확률이 없어야 합니다

2024-10-07 01:04 UTC, owjs3901 commented on .dumi/theme/builtins/Previewer/CodePreviewer.tsx
> +      <html lang="ko">
넘어가기 쉬웠을 텐데, 꼼꼼해서 좋습니다

2024-10-07 07:28 UTC, Banal972 commented on .dumi/theme/builtins/LocaleLink/index.tsx
> +      if (localeType === 'ko' && !path.endsWith('-ko')) {
아 제가 놓친부분이 있었네요!

2024-10-07 07:29 UTC, Banal972 commented on .dumi/pages/404/index.tsx
> +      subTitle="Sorry, the page you visited does not exist."
아! 수정해보겠습니다

2024-10-07 07:29 UTC, Banal972 commented on .dumi/hooks/useLocation.ts
> +  return path.replace('', '').replace(/\/$/, '');
넵! 감사합니당

2024-10-07 07:29 UTC, Banal972 commented on .dumi/hooks/useLocation.ts
>    const [, localeType] = useLocale();
이 부분은 조금 더 생각해볼게요!

2024-10-08 05:18 UTC, owjs3901 approved these changes

2024-10-08 05:43 UTC, merged