components button md 파일 번역
ant-design-korea/ant-design pull request #26
Opened 2024-10-07 08:58 UTC by yeon-dong

## 💻 Feature 설명
> Components의 Button의 index.ko-KR.md 파일 번역 완료
<br>

## 📝 To-do
**메인주제**
- [x] index.ko-KR.md 파일 번역
<br>

## 📸 스크린샷
![image](https://github.com/user-attachments/assets/569e40fc-262b-4525-9123-e7ba5710afb3)

<br>

## 📚 참고문헌 / 기타
-

2024-10-07 09:00 UTC, yeon-dong commented
일단 큼지막한 md 파일 수정했고, 이후 tsx 파일과 연관된 부분들 ex) basic.md 도 추후 번역 예정입니다.

2024-10-07 11:12 UTC, owjs3901 requested changes

2024-10-08 00:31 UTC, yeon-dong commented on components/button/demo/basic.tsx
> +    <Button type="dashed">Dashed Button12</Button>
헉 까먹었네요 확인 감사합니다!

2024-10-08 00:32 UTC, yeon-dong commented on components/button/index.ko-KR.md
> +| htmlType | Set the original html `type` of `button`, see: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type) | string | `button` |  |
위의 문법에 따르면 en-US 인데 그냥 ko로 하면 될까요?

2024-10-08 02:07 UTC, merged