feat: ComponentsList.tsx 번역
ant-design-korea/ant-design pull request #46
Opened 2024-10-16 01:30 UTC by haeunnam

[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [ ] 🐞 Bug fix
- [✓ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 📝 Change Log

ComponentList 번역

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

2024-10-18 10:11 UTC, owjs3901 requested changes

2024-10-18 10:11 UTC, owjs3901 commented on .dumi/pages/index/index.tsx
> +git;
오타 같습니다.

2024-10-21 14:12 UTC, haeunnam commented on .dumi/pages/index/index.tsx
> +git;
수정했습니다!

2024-10-23 12:13 UTC, owjs3901 approved these changes

2024-10-23 12:13 UTC, merged